<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <relativePath>../../../PlatformDependencies</relativePath>
        <artifactId>platform-dependencies</artifactId>
        <groupId>ru.pashutin</groupId>
        <version>1.5.1</version>
    </parent>
    <artifactId>business-ai-processing</artifactId>
    <packaging>pom</packaging>

    <name>Business AI Processing</name>

    <description>Фоновое исполнение задач искусственного интеллекта</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ru.pashutin</groupId>
                <artifactId>platform-dependencies</artifactId>
                <version>${project.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>pipenv</executable>
                    <arguments>
                        <argument>requirements</argument>
                    </arguments>
                    <outputFile>${project.basedir}\requirements.txt</outputFile>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>